<?php
/**
 * Debug Script for URL Generation
 * Check what URLs are being generated by base_url() and site_url()
 */

// Set proper environment
putenv('CI_ENVIRONMENT=development');

// Load CodeIgniter
require_once 'vendor/autoload.php';

// Bootstrap CodeIgniter properly
$app = \Config\Services::codeigniter();
$app->initialize();

echo "🔍 URL Generation Debug\n";
echo "====================\n\n";

try {
    // Test URL generation functions
    echo "1. Testing URL Generation Functions:\n";
    echo "-----------------------------------\n";
    
    echo "base_url(): " . base_url() . "\n";
    echo "base_url('/'): " . base_url('/') . "\n";
    echo "base_url('dashboard'): " . base_url('dashboard') . "\n";
    echo "base_url('auth/login'): " . base_url('auth/login') . "\n";
    
    echo "\nsite_url(): " . site_url() . "\n";
    echo "site_url('dashboard'): " . site_url('dashboard') . "\n";
    
    // Test configuration
    echo "\n2. Configuration Values:\n";
    echo "----------------------\n";
    
    $config = config('App');
    echo "App baseURL: " . $config->baseURL . "\n";
    
    // Test with $_SERVER simulation
    echo "\n3. Server Environment:\n";
    echo "--------------------\n";
    echo "HTTP_HOST: " . ($_SERVER['HTTP_HOST'] ?? 'Not set') . "\n";
    echo "REQUEST_URI: " . ($_SERVER['REQUEST_URI'] ?? 'Not set') . "\n";
    echo "SCRIPT_NAME: " . ($_SERVER['SCRIPT_NAME'] ?? 'Not set') . "\n";
    
    // Test what happens with redirect
    echo "\n4. Testing Redirect URLs:\n";
    echo "-----------------------\n";
    
    // Simulate getDashboardRedirectUrl
    $testUser = ['id' => 1, 'username' => 'admin'];
    
    $redirectToRoot = base_url('/');
    $redirectToDashboard = base_url('dashboard');
    
    echo "Redirect to root ('/'): $redirectToRoot\n";
    echo "Redirect to dashboard: $redirectToDashboard\n";
    
    echo "\n✅ URL generation test completed successfully!\n";
    
} catch (Exception $e) {
    echo "❌ Error: " . $e->getMessage() . "\n";
    echo "File: " . $e->getFile() . " Line: " . $e->getLine() . "\n";
    echo "Stack trace:\n" . $e->getTraceAsString() . "\n";
}
?>